CREATE DATABASE IF NOT EXISTS stockwise;
USE stockwise;

CREATE TABLE IF NOT EXISTS wallet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  balance DECIMAL(20, 2) NOT NULL DEFAULT 1000000.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  avg_buy_price DECIMAL(20, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE(symbol)
);

CREATE TABLE IF NOT EXISTS trades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type ENUM('BUY', 'SELL') NOT NULL,
  price DECIMAL(20, 2) NOT NULL,
  quantity INT NOT NULL,
  total DECIMAL(20, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  date DATE NOT NULL,
  open DECIMAL(20, 2),
  high DECIMAL(20, 2),
  low DECIMAL(20, 2),
  close DECIMAL(20, 2),
  volume BIGINT,
  UNIQUE(symbol, date)
);

CREATE TABLE IF NOT EXISTS watchlist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(symbol)
);

CREATE TABLE IF NOT EXISTS stock_views (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(255) NOT NULL,
  current_price DECIMAL(20, 2),
  day_high DECIMAL(20, 2),
  day_low DECIMAL(20, 2),
  viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Initialize wallet if it doesn't exist
INSERT INTO wallet (balance) SELECT 1000000.00 WHERE NOT EXISTS (SELECT 1 FROM wallet);
